### PR TITLE
add SingleSelectElement component

### LINKED ISSUE #47: add component for single select
we already have the multi-select component (https://api.slack.com/reference/block-kit/block-elements#multi_select)
but we do not have https://api.slack.com/reference/block-kit/block-elements#select

### PR DESCRIPTION
**Pull request by davemeyer**
add a new component for the [single select slack block](https://api.slack.com/reference/block-kit/block-elements#select)
our existing `SelectElement` was a multi-select component for the [multi select slack block](https://api.slack.com/reference/block-kit/block-elements#multi_select)

so rename what was `SelectElement` to `MultiSelectElement`
and the new single select is called `SingleSelectElement` so we are explicit about the use cases

closes: #47

### CODE REVIEW

**Review by andycmaj — APPROVED** [review]
thanks for fixing the naming here

**Review by andycmaj — APPROVED** [review]
I think you might have forgotten to add to exports in index. ts actually

**Comment by davemeyer** [comment]
> I think you might have forgotten to add to exports in index. ts actually

@andycmaj  i put the single and multi select in the same file. but can update for consistent 1:1 mapping. but as-is, we do a `export * from './SelectElement';` so it is already exported

**Comment by andycmaj** [comment]
right on. thanks!

**Pull request merged**
